media: 
  input: site/img
  output: img

content:
  - name: home
    label: Home Page
    path: site/index.md
    type: file
    format: raw
    fields:
      - name: image
        label: Pretty Picture
        type: image
      - name: body
        label: Page Text
        type: text
