media: 
  input: site/img
  output: img

content:
  - name: pages
    label: Pages
    path: site
    type: collection
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: image, label: Banner, type: image }
      - { name: body, label: Page Text, type: rich-text }
